default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: DPAPI_development

test:
  <<: *default
  database: DPAPI_test

production:
  <<: *default
  database: DPAPI_production
  username: DPAPI
  password: <%= ENV['DPAPI_DATABASE_PASSWORD'] %>
